advanced_settings:
  brownfield: false
  capacity_expansion: false
  cost_of_debt: 0.11
  cost_of_equity: 0.12
  debt_share: 0.9
  equity_share: 0.1
  grid_availability_simulation: false
  grid_connection: false
  grid_connection_type: 0
  milp_formulation: true
  min_step_duration: 1
  multi_scenario_optimization: false
  multiobjective_optimization: false
  num_scenarios: 1
  num_steps: 1
  pareto_points: 2
  scenario_weights:
  - 1.0
  step_duration: 20
  tax: 0.02
  unit_commitment: false
  wacc_calculation: false
archetypes_params:
  cooling_period: AY
  demand_growth: 0.0
  h_tier1: 252
  h_tier2: 160
  h_tier3: 50
  h_tier4: 36
  h_tier5: 5
  hospital_1: 0
  hospital_2: 1
  hospital_3: 0
  hospital_4: 0
  hospital_5: 0
  schools: 1
battery_params:
  battery_charge_battery_efficiency: 0.95
  battery_chemistry: LFP
  battery_cycles: 5000
  battery_depth_of_discharge: 0.8
  battery_discharge_battery_efficiency: 0.95
  battery_existing_capacity: 0.0
  battery_expected_lifetime: 10
  battery_initial_soc: 1.0
  battery_nominal_capacity: 1000.0
  battery_specific_electronic_investment_cost: 0.1
  battery_specific_investment_cost: 0.3
  battery_specific_om_cost: 0.02
  bess_unit_co2_emission: 0.0
  maximum_battery_charge_time: 3.0
  maximum_battery_discharge_time: 3.0
nasa_power_params:
  base_url: https://power.larc.nasa.gov/api/temporal/
  community: RE
  date_end: '20201231'
  date_start: '20150101'
  loc_id: point
  output_format: JSON
  parameters_1: ALLSKY_SFC_SW_DWN
  parameters_2: T2MWET,T2M,WS50M
  parameters_3: WS50M,WS2M,WD50M,T2M
  temp_res_1: daily
  temp_res_2: hourly
  user: anonymous
project_info:
  project_description: ''
  project_name: test
project_settings:
  battery_independence: 0
  discount_rate: 0.1
  investment_cost_limit: 500000.0
  land_availability: 0.0
  lost_load_fraction: 0.0
  lost_load_specific_cost: 0.0
  optimization_goal: 0
  renewable_penetration: 0.0
  solver: 0
  start_date: 2023-01-01 00:00:00
  system_configuration: 0
  time_horizon: 20
  time_resolution: 8760
renewables_params:
  res_existing_area:
  - 0.0
  res_existing_capacity:
  - 0.0
  res_existing_years:
  - 0
  res_inverter_efficiency:
  - 0.98
  res_lifetime:
  - 20
  res_names:
  - Solar PV
  res_nominal_capacity:
  - 1000.0
  res_sources: 1
  res_specific_area:
  - 11.49
  res_specific_investment_cost:
  - 0.95
  res_specific_om_cost:
  - 0.018
  res_unit_co2_emission:
  - 0.0
resource_assessment:
  G_NMOT: 800
  NMOT: 45
  T_NMOT: 20
  azim: 180
  drivetrain_efficiency: 0.9
  k_T: -0.37
  lat: -11.56567
  location: Nairobi, Kenya
  lon: 34.23567
  nom_power: 1000
  ro_ground: 0.2
  tilt: 10
  time_zone: 2
  turbine_model: NPS100c-21
  turbine_type: Horizontal Axis
